name: AWS Login
description: Login to AWS

inputs:
  aws-access-key-id:
    description: >-
      AWS Access Key ID. This input is required if running in the GitHub hosted environment.
    required: true
  aws-secret-access-key:
    description: >-
      AWS Secret Access Key. This input is required if running in the GitHub hosted environment.
    required: true
  aws-region:
    description: 'AWS Region, e.g. us-east-2'
    required: true

runs:
  using: composite
  steps:
    -
      name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

#    -
#      name: Display AWS auth ID
#      run: aws sts get-caller-identity
#      shell: bash
