# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Example - Composite Action

on:
  # workflow_dispatch is a manually invoked workflow
  workflow_dispatch:

jobs:
  composite_action_caller:
    runs-on: ubuntu-latest
    steps:
      # Need to check out code before using local composite actions
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Calling composite action step
        uses: ./.github/actions/composite-action