name: GHA Matrix Examples
on:
  workflow_dispatch:

jobs:
  test_matrix_b:
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: true
      matrix:
        type_b: [type_b_00, type_b_01, type_b_02]

    steps:
      -
        name: Step One
        run: |
          if [[ "${{ matrix.type_b }}" == "type_b_01" ]]; then
            echo "FAIL Step One: key:${{ matrix.type_b }}" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "Step One: key:${{ matrix.type_b }}" >> $GITHUB_STEP_SUMMARY
          fi

      -
        name: Step Two
        run: |
          sleep 60
          echo "Step Two: key:${{ matrix.type_b }}" >> $GITHUB_STEP_SUMMARY
