name: GHA Matrix Examples
on:
  workflow_dispatch:

jobs:
  test_matrix_a:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type_x: [type_x_00, type_x_01, type_x_02]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Print type_x
        run: |
          echo "type_x key:${{ matrix.type_x }}" >> $GITHUB_STEP_SUMMARY

  test_matrix_b:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type_b: [type_b_00, type_b_01, type_b_02]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Print type_b
        run: |
          echo "type_b key:${{ matrix.type_b }}" >> $GITHUB_STEP_SUMMARY
