name: GHA Matrix Examples
on:
  workflow_dispatch:

jobs:
  test_matrix_a:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type_x: [type_x_00, type_x_01, type_x_02]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Print type_x
        run: |
          echo "type_x key:${{ matrix.type_x }}"

  test_matrix_b:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type_a: [type_a_00, type_a_01, type_a_02]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Print type_a
        run: |
          echo "type_a key:${{ matrix.type_a }}"
